### ISSUE TITLE
Make image upload skin editable again 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [antville/antville#92]
```
... to be able to enforce a max. width/length other than 400 px, offer tags
to be inserted by klicking, etc.pp. 

```

Original issue reported on code.google.com by `kinomu.w...@gmail.com` on 14 Mar 2010 at 4:09

**Comment by p3k** [comment]
since 0a0f1fc376071794946a5becbc7c3f0707f5829b max. width and height values for images are available on the settings page. other options (like offering tags) should be possible to implement via client-side scripts; closing as wontfix.
